# Generated by Django 4.2.4 on 2023-11-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(default='2023-11-10')),
                ('home', models.TextField(null=True)),
                ('tree', models.TextField(null=True)),
                ('person', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_house/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_person/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_tree/')),
            ],
        ),
    ]
