# Generated by Django 4.2.4 on 2023-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HTP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now=True)),
                ('home', models.TextField()),
                ('tree', models.TextField()),
                ('person', models.TextField()),
            ],
        ),
    ]
