# Generated by Django 4.2.4 on 2023-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htp_test', '0003_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_house/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_person/')),
            ],
        ),
        migrations.CreateModel(
            name='Image_tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_tree/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
