# Generated by Django 4.2.4 on 2023-11-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('htp_test', '0004_image_house_image_person_image_tree_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='htp',
            name='user_id',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자아이디'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='htp',
            name='created_date',
            field=models.DateField(auto_now=True, verbose_name='생성날짜'),
        ),
        migrations.AlterField(
            model_name='htp',
            name='home',
            field=models.TextField(null=True, verbose_name='집결과'),
        ),
        migrations.AlterField(
            model_name='htp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='htp',
            name='person',
            field=models.TextField(null=True, verbose_name='사람결과'),
        ),
        migrations.AlterField(
            model_name='htp',
            name='tree',
            field=models.TextField(null=True, verbose_name='나무결과'),
        ),
    ]
