# Generated by Django 4.2.4 on 2023-11-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htp_test', '0005_htp_user_id'),
        ('htp_test', '0005_htp_user_id_alter_htp_created_date_alter_htp_home_and_more'),
    ]

    operations = [
    ]
