# Generated by Django 4.2.4 on 2023-11-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('htp_test', '0006_merge_20231108_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htp',
            name='created_date',
            field=models.DateField(default='2023-11-08'),
        ),
        migrations.AlterField(
            model_name='htp',
            name='home',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='htp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='htp',
            name='person',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='htp',
            name='tree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='htp',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
    ]
