# Generated by Django 4.2.4 on 2023-11-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htp_test', '0005_htp_user_id'),
        ('htp_test', '0006_alter_htp_user_id'),
    ]

    operations = [
    ]
