# Generated by Django 4.2.4 on 2023-11-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htp_test', '0006_alter_htp_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htp',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
