# Generated by Django 4.2.4 on 2023-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htp_test', '0007_alter_htp_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htp',
            name='created_date',
            field=models.DateField(default='2023-11-08'),
        ),
    ]
