# Generated by Django 4.2.4 on 2023-10-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_managers_member_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=128, verbose_name='이름'),
        ),
    ]
